//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIDS.MOBILE.APP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIDS.MOBILE.APP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string _00001 {
            get {
                return ResourceManager.GetString("00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string _00002 {
            get {
                return ResourceManager.GetString("00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember account.
        /// </summary>
        internal static string _00003 {
            get {
                return ResourceManager.GetString("00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER.
        /// </summary>
        internal static string _00004 {
            get {
                return ResourceManager.GetString("00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        internal static string _00005 {
            get {
                return ResourceManager.GetString("00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password.
        /// </summary>
        internal static string _00006 {
            get {
                return ResourceManager.GetString("00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string _00007 {
            get {
                return ResourceManager.GetString("00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine reminders.
        /// </summary>
        internal static string _00008 {
            get {
                return ResourceManager.GetString("00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence request.
        /// </summary>
        internal static string _00009 {
            get {
                return ResourceManager.GetString("00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string _00010 {
            get {
                return ResourceManager.GetString("00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string _00011 {
            get {
                return ResourceManager.GetString("00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string _00012 {
            get {
                return ResourceManager.GetString("00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESCRIPTION.
        /// </summary>
        internal static string _00013 {
            get {
                return ResourceManager.GetString("00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string _00014 {
            get {
                return ResourceManager.GetString("00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string _00015 {
            get {
                return ResourceManager.GetString("00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher notes.
        /// </summary>
        internal static string _00016 {
            get {
                return ResourceManager.GetString("00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        internal static string _00017 {
            get {
                return ResourceManager.GetString("00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of medicine.
        /// </summary>
        internal static string _00018 {
            get {
                return ResourceManager.GetString("00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string _00019 {
            get {
                return ResourceManager.GetString("00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string _00020 {
            get {
                return ResourceManager.GetString("00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string _00021 {
            get {
                return ResourceManager.GetString("00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Management.
        /// </summary>
        internal static string _00022 {
            get {
                return ResourceManager.GetString("00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string _00023 {
            get {
                return ResourceManager.GetString("00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string _00024 {
            get {
                return ResourceManager.GetString("00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a good working day, {0}.
        /// </summary>
        internal static string _00025 {
            get {
                return ResourceManager.GetString("00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string _00026 {
            get {
                return ResourceManager.GetString("00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string _00027 {
            get {
                return ResourceManager.GetString("00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily works.
        /// </summary>
        internal static string _00028 {
            get {
                return ResourceManager.GetString("00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New post.
        /// </summary>
        internal static string _00029 {
            get {
                return ResourceManager.GetString("00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string _00030 {
            get {
                return ResourceManager.GetString("00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        internal static string _00031 {
            get {
                return ResourceManager.GetString("00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napping.
        /// </summary>
        internal static string _00032 {
            get {
                return ResourceManager.GetString("00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dining.
        /// </summary>
        internal static string _00033 {
            get {
                return ResourceManager.GetString("00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hygiene.
        /// </summary>
        internal static string _00034 {
            get {
                return ResourceManager.GetString("00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment.
        /// </summary>
        internal static string _00035 {
            get {
                return ResourceManager.GetString("00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string _00036 {
            get {
                return ResourceManager.GetString("00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string _00037 {
            get {
                return ResourceManager.GetString("00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent at.
        /// </summary>
        internal static string _00038 {
            get {
                return ResourceManager.GetString("00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string _00039 {
            get {
                return ResourceManager.GetString("00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfimred.
        /// </summary>
        internal static string _00040 {
            get {
                return ResourceManager.GetString("00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string _00041 {
            get {
                return ResourceManager.GetString("00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student management.
        /// </summary>
        internal static string _00042 {
            get {
                return ResourceManager.GetString("00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create evaluation board.
        /// </summary>
        internal static string _00043 {
            get {
                return ResourceManager.GetString("00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evalution.
        /// </summary>
        internal static string _00044 {
            get {
                return ResourceManager.GetString("00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string _00045 {
            get {
                return ResourceManager.GetString("00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string _00046 {
            get {
                return ResourceManager.GetString("00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string _00047 {
            get {
                return ResourceManager.GetString("00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string _00048 {
            get {
                return ResourceManager.GetString("00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _00049 {
            get {
                return ResourceManager.GetString("00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to log out of this account.
        /// </summary>
        internal static string _00050 {
            get {
                return ResourceManager.GetString("00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study plan.
        /// </summary>
        internal static string _00051 {
            get {
                return ResourceManager.GetString("00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height and weight.
        /// </summary>
        internal static string _00052 {
            get {
                return ResourceManager.GetString("00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string _00053 {
            get {
                return ResourceManager.GetString("00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new post.
        /// </summary>
        internal static string _00054 {
            get {
                return ResourceManager.GetString("00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string _00055 {
            get {
                return ResourceManager.GetString("00055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News content.
        /// </summary>
        internal static string _00056 {
            get {
                return ResourceManager.GetString("00056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News title.
        /// </summary>
        internal static string _00057 {
            get {
                return ResourceManager.GetString("00057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post details.
        /// </summary>
        internal static string _00058 {
            get {
                return ResourceManager.GetString("00058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album details.
        /// </summary>
        internal static string _00059 {
            get {
                return ResourceManager.GetString("00059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during processing.
        /// </summary>
        internal static string _00060 {
            get {
                return ResourceManager.GetString("00060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string _00061 {
            get {
                return ResourceManager.GetString("00061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to confirm this prescription !.
        /// </summary>
        internal static string _00062 {
            get {
                return ResourceManager.GetString("00062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string _00063 {
            get {
                return ResourceManager.GetString("00063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string _00064 {
            get {
                return ResourceManager.GetString("00064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDICINE TO BE TAKEN.
        /// </summary>
        internal static string _00065 {
            get {
                return ResourceManager.GetString("00065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of medicine prescription.
        /// </summary>
        internal static string _00066 {
            get {
                return ResourceManager.GetString("00066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string _00067 {
            get {
                return ResourceManager.GetString("00067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On class.
        /// </summary>
        internal static string _00068 {
            get {
                return ResourceManager.GetString("00068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excused absence.
        /// </summary>
        internal static string _00069 {
            get {
                return ResourceManager.GetString("00069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexcused absence.
        /// </summary>
        internal static string _00070 {
            get {
                return ResourceManager.GetString("00070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        internal static string _00071 {
            get {
                return ResourceManager.GetString("00071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come.
        /// </summary>
        internal static string _00073 {
            get {
                return ResourceManager.GetString("00073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string _00074 {
            get {
                return ResourceManager.GetString("00074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        internal static string _00075 {
            get {
                return ResourceManager.GetString("00075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note….
        /// </summary>
        internal static string _00076 {
            get {
                return ResourceManager.GetString("00076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        internal static string _00077 {
            get {
                return ResourceManager.GetString("00077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a picker.
        /// </summary>
        internal static string _00078 {
            get {
                return ResourceManager.GetString("00078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker.
        /// </summary>
        internal static string _00079 {
            get {
                return ResourceManager.GetString("00079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unselect all.
        /// </summary>
        internal static string _00080 {
            get {
                return ResourceManager.GetString("00080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        internal static string _00081 {
            get {
                return ResourceManager.GetString("00081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add album.
        /// </summary>
        internal static string _00082 {
            get {
                return ResourceManager.GetString("00082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string _00083 {
            get {
                return ResourceManager.GetString("00083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string _00084 {
            get {
                return ResourceManager.GetString("00084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string _00085 {
            get {
                return ResourceManager.GetString("00085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string _00086 {
            get {
                return ResourceManager.GetString("00086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string _00087 {
            get {
                return ResourceManager.GetString("00087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string _00088 {
            get {
                return ResourceManager.GetString("00088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child profile.
        /// </summary>
        internal static string _00089 {
            get {
                return ResourceManager.GetString("00089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        internal static string _00090 {
            get {
                return ResourceManager.GetString("00090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        internal static string _00091 {
            get {
                return ResourceManager.GetString("00091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher profile.
        /// </summary>
        internal static string _00092 {
            get {
                return ResourceManager.GetString("00092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast.
        /// </summary>
        internal static string _00093 {
            get {
                return ResourceManager.GetString("00093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch.
        /// </summary>
        internal static string _00094 {
            get {
                return ResourceManager.GetString("00094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snack.
        /// </summary>
        internal static string _00095 {
            get {
                return ResourceManager.GetString("00095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinner.
        /// </summary>
        internal static string _00096 {
            get {
                return ResourceManager.GetString("00096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string _00097 {
            get {
                return ResourceManager.GetString("00097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string _00098 {
            get {
                return ResourceManager.GetString("00098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default sleeping time.
        /// </summary>
        internal static string _00099 {
            get {
                return ResourceManager.GetString("00099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Picker.
        /// </summary>
        internal static string _00100 {
            get {
                return ResourceManager.GetString("00100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstable connection, please check network connection !.
        /// </summary>
        internal static string _00101 {
            get {
                return ResourceManager.GetString("00101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album title.
        /// </summary>
        internal static string _00102 {
            get {
                return ResourceManager.GetString("00102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defecation count.
        /// </summary>
        internal static string _00103 {
            get {
                return ResourceManager.GetString("00103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily assessment.
        /// </summary>
        internal static string _00104 {
            get {
                return ResourceManager.GetString("00104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly assessment.
        /// </summary>
        internal static string _00105 {
            get {
                return ResourceManager.GetString("00105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sticker.
        /// </summary>
        internal static string _00106 {
            get {
                return ResourceManager.GetString("00106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pictures selected.
        /// </summary>
        internal static string _00107 {
            get {
                return ResourceManager.GetString("00107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No picture seleted.
        /// </summary>
        internal static string _00108 {
            get {
                return ResourceManager.GetString("00108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string _00109 {
            get {
                return ResourceManager.GetString("00109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student code.
        /// </summary>
        internal static string _00110 {
            get {
                return ResourceManager.GetString("00110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student&apos;s name.
        /// </summary>
        internal static string _00111 {
            get {
                return ResourceManager.GetString("00111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plysical.
        /// </summary>
        internal static string _00112 {
            get {
                return ResourceManager.GetString("00112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awareness.
        /// </summary>
        internal static string _00113 {
            get {
                return ResourceManager.GetString("00113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string _00114 {
            get {
                return ResourceManager.GetString("00114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remonce - Society.
        /// </summary>
        internal static string _00115 {
            get {
                return ResourceManager.GetString("00115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        internal static string _00116 {
            get {
                return ResourceManager.GetString("00116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student assessment.
        /// </summary>
        internal static string _00117 {
            get {
                return ResourceManager.GetString("00117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation board.
        /// </summary>
        internal static string _00118 {
            get {
                return ResourceManager.GetString("00118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targets.
        /// </summary>
        internal static string _00119 {
            get {
                return ResourceManager.GetString("00119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string _00120 {
            get {
                return ResourceManager.GetString("00120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string _00121 {
            get {
                return ResourceManager.GetString("00121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commet.
        /// </summary>
        internal static string _00122 {
            get {
                return ResourceManager.GetString("00122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Details.
        /// </summary>
        internal static string _00123 {
            get {
                return ResourceManager.GetString("00123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a comment….
        /// </summary>
        internal static string _00124 {
            get {
                return ResourceManager.GetString("00124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose people.
        /// </summary>
        internal static string _00125 {
            get {
                return ResourceManager.GetString("00125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message.
        /// </summary>
        internal static string _00126 {
            get {
                return ResourceManager.GetString("00126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string _00127 {
            get {
                return ResourceManager.GetString("00127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string _00128 {
            get {
                return ResourceManager.GetString("00128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string _00129 {
            get {
                return ResourceManager.GetString("00129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date picker.
        /// </summary>
        internal static string _00130 {
            get {
                return ResourceManager.GetString("00130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string _00131 {
            get {
                return ResourceManager.GetString("00131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string _00132 {
            get {
                return ResourceManager.GetString("00132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string _00133 {
            get {
                return ResourceManager.GetString("00133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string _00134 {
            get {
                return ResourceManager.GetString("00134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string _00135 {
            get {
                return ResourceManager.GetString("00135", resourceCulture);
            }
        }
    }
}
